name = "VEnv"
uuid = "edc963e9-dcda-4f66-9026-82f0eeff0a32"
authors = ["Christopher Doris <github.com/cjdoris> and contributors"]
version = "0.1.0"

[deps]
Pidfile = "fa939f87-e72e-5be4-a000-7fc836dbe307"
Python_jll = "93d3a430-8e7c-50da-8e8d-3dfcfb3baf05"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
