name = "PythonVEnv"
uuid = "edc963e9-dcda-4f66-9026-82f0eeff0a32"
authors = ["Christopher Doris <github.com/cjdoris> and contributors"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
